# Generated by Django 3.0.6 on 2020-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JsonFile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
